// <auto-generated />
using System;
using CodeDocs_Challenge.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CodeDocs_Challenge.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190610204514_Version2")]
    partial class Version2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("CodeDocs_Challenge.Models.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ContentHtml");

                    b.Property<string>("ContentMD");

                    b.Property<DateTime>("Created");

                    b.Property<string>("ImgBlob");

                    b.Property<string>("Language");

                    b.Property<DateTime>("LastEdited");

                    b.Property<string>("Name");

                    b.Property<string>("SourceUrl");

                    b.HasKey("Id");

                    b.ToTable("Articles");
                });
#pragma warning restore 612, 618
        }
    }
}
